name: v_prism
channels:
- conda-forge
- nvidia
- pytorch
- defaults
- pyg
dependencies:
- python>=3.10
- nvidia::cudatoolkit
- pytorch::torchvision
- pytorch=2.0.1
- numpy
- matplotlib
- scipy
- requests
- tqdm
- trimesh
- scikit-image
- jupyter
- pyg::pytorch-cluster
- pyg::pyg
- conda-forge::rtree
- opencv
- pip
- pip:
  - pyglet<2
  - point-cloud-utils

  